# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GBShop' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GBShop
  pod 'Alamofire', '~> 4.9.1'
  pod 'YandexMobileMetrica', '3.14.0'

  target 'GBShopTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'GBShopUITests' do
    # Pods for testing
  end

end
